version: '3.9'
services:
    backend:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:5.7
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            MYSQL_DATABASE: petitions
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
            - ./storage/db:/var/lib/mysql
        ports:
            - "3307:3306"

    redis:
        image: redis
        ports:
            - "6379:6379"
